name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build application
        run: |
          # Commands to compile your Java application
          javac -d target ./src/junit/monprojet/*.java

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install JUnit
        run: |
          # Commands to install JUnit
          mkdir lib
          curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
          mv junit-platform-console-standalone-1.8.2.jar lib/

      - name: Run automated tests
        run: |
          # Commands to run automated tests with JUnit
          java -jar lib/junit-platform-console-standalone-1.8.2.jar --class-path target --scan-class-path

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [test] # This job depends on the 'test' job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Deploy to production
      #   run: |
      #     # Commands to deploy your application to a production environment
      #     # Example: Use tools like Docker, Ansible, or simply copy files to a server
